//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Parameter 'SendDateTime' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SocialMediaLikeTelegram.ServiceReference1.SendResponse Send(SocialMediaLikeTelegram.ServiceReference1.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<SocialMediaLikeTelegram.ServiceReference1.SendResponse> SendAsync(SocialMediaLikeTelegram.ServiceReference1.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Receive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Receive(string username, string password, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Receive", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceiveAsync(string username, string password, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Status(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Status", ReplyAction="*")]
        System.Threading.Tasks.Task<string> StatusAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDelivery(string RefID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDeliveryAsync(string RefID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool flash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public bool Unicode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public bool encode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SendDateTime;
        
        public SendRequest() {
        }
        
        public SendRequest(string username, string password, string Number, string recipient, string body, bool flash, bool Unicode, bool encode, System.Nullable<System.DateTime> SendDateTime) {
            this.username = username;
            this.password = password;
            this.Number = Number;
            this.recipient = recipient;
            this.body = body;
            this.flash = flash;
            this.Unicode = Unicode;
            this.encode = encode;
            this.SendDateTime = SendDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SendResult;
        
        public SendResponse() {
        }
        
        public SendResponse(string SendResult) {
            this.SendResult = SendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap>, SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocialMediaLikeTelegram.ServiceReference1.SendResponse SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap.Send(SocialMediaLikeTelegram.ServiceReference1.SendRequest request) {
            return base.Channel.Send(request);
        }
        
        public string Send(string username, string password, string Number, string recipient, string body, bool flash, bool Unicode, bool encode, System.Nullable<System.DateTime> SendDateTime) {
            SocialMediaLikeTelegram.ServiceReference1.SendRequest inValue = new SocialMediaLikeTelegram.ServiceReference1.SendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.Number = Number;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.flash = flash;
            inValue.Unicode = Unicode;
            inValue.encode = encode;
            inValue.SendDateTime = SendDateTime;
            SocialMediaLikeTelegram.ServiceReference1.SendResponse retVal = ((SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap)(this)).Send(inValue);
            return retVal.SendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SocialMediaLikeTelegram.ServiceReference1.SendResponse> SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap.SendAsync(SocialMediaLikeTelegram.ServiceReference1.SendRequest request) {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SocialMediaLikeTelegram.ServiceReference1.SendResponse> SendAsync(string username, string password, string Number, string recipient, string body, bool flash, bool Unicode, bool encode, System.Nullable<System.DateTime> SendDateTime) {
            SocialMediaLikeTelegram.ServiceReference1.SendRequest inValue = new SocialMediaLikeTelegram.ServiceReference1.SendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.Number = Number;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.flash = flash;
            inValue.Unicode = Unicode;
            inValue.encode = encode;
            inValue.SendDateTime = SendDateTime;
            return ((SocialMediaLikeTelegram.ServiceReference1.WebServiceSoap)(this)).SendAsync(inValue);
        }
        
        public string Receive(string username, string password, int qty) {
            return base.Channel.Receive(username, password, qty);
        }
        
        public System.Threading.Tasks.Task<string> ReceiveAsync(string username, string password, int qty) {
            return base.Channel.ReceiveAsync(username, password, qty);
        }
        
        public string Status(string username, string password) {
            return base.Channel.Status(username, password);
        }
        
        public System.Threading.Tasks.Task<string> StatusAsync(string username, string password) {
            return base.Channel.StatusAsync(username, password);
        }
        
        public string GetDelivery(string RefID) {
            return base.Channel.GetDelivery(RefID);
        }
        
        public System.Threading.Tasks.Task<string> GetDeliveryAsync(string RefID) {
            return base.Channel.GetDeliveryAsync(RefID);
        }
    }
}
