//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialMediaDBEntities : DbContext
    {
        public SocialMediaDBEntities()
            : base("name=SocialMediaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_ActivationCode> tbl_ActivationCode { get; set; }
        public virtual DbSet<tbl_BlockList> tbl_BlockList { get; set; }
        public virtual DbSet<tbl_CahnnelAdmins> tbl_CahnnelAdmins { get; set; }
        public virtual DbSet<tbl_ChannelMembers> tbl_ChannelMembers { get; set; }
        public virtual DbSet<tbl_ChannelMessages> tbl_ChannelMessages { get; set; }
        public virtual DbSet<tbl_Channels> tbl_Channels { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_Emoji> tbl_Emoji { get; set; }
        public virtual DbSet<tbl_GroupAdmin> tbl_GroupAdmin { get; set; }
        public virtual DbSet<tbl_GroupBanList> tbl_GroupBanList { get; set; }
        public virtual DbSet<tbl_GroupMembers> tbl_GroupMembers { get; set; }
        public virtual DbSet<tbl_GroupMessage> tbl_GroupMessage { get; set; }
        public virtual DbSet<tbl_Groups> tbl_Groups { get; set; }
        public virtual DbSet<tbl_Message> tbl_Message { get; set; }
        public virtual DbSet<tbl_OpenSessions> tbl_OpenSessions { get; set; }
        public virtual DbSet<tbl_Pic> tbl_Pic { get; set; }
        public virtual DbSet<tbl_PrivateChat> tbl_PrivateChat { get; set; }
        public virtual DbSet<tbl_PrivateChatMessage> tbl_PrivateChatMessage { get; set; }
        public virtual DbSet<tbl_Seen> tbl_Seen { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int CreateChannel(string channel_Name, Nullable<int> channel_Type, string channel_ID, string inviteLink, Nullable<long> pic_id, string des, Nullable<long> creator_id)
        {
            var channel_NameParameter = channel_Name != null ?
                new ObjectParameter("Channel_Name", channel_Name) :
                new ObjectParameter("Channel_Name", typeof(string));
    
            var channel_TypeParameter = channel_Type.HasValue ?
                new ObjectParameter("Channel_Type", channel_Type) :
                new ObjectParameter("Channel_Type", typeof(int));
    
            var channel_IDParameter = channel_ID != null ?
                new ObjectParameter("Channel_ID", channel_ID) :
                new ObjectParameter("Channel_ID", typeof(string));
    
            var inviteLinkParameter = inviteLink != null ?
                new ObjectParameter("InviteLink", inviteLink) :
                new ObjectParameter("InviteLink", typeof(string));
    
            var pic_idParameter = pic_id.HasValue ?
                new ObjectParameter("Pic_id", pic_id) :
                new ObjectParameter("Pic_id", typeof(long));
    
            var desParameter = des != null ?
                new ObjectParameter("Des", des) :
                new ObjectParameter("Des", typeof(string));
    
            var creator_idParameter = creator_id.HasValue ?
                new ObjectParameter("Creator_id", creator_id) :
                new ObjectParameter("Creator_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateChannel", channel_NameParameter, channel_TypeParameter, channel_IDParameter, inviteLinkParameter, pic_idParameter, desParameter, creator_idParameter);
        }
    }
}
