//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Groups()
        {
            this.tbl_GroupAdmin = new HashSet<tbl_GroupAdmin>();
            this.tbl_GroupBanList = new HashSet<tbl_GroupBanList>();
            this.tbl_GroupMembers = new HashSet<tbl_GroupMembers>();
            this.tbl_GroupMessage = new HashSet<tbl_GroupMessage>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string InviteLink { get; set; }
        public string Description { get; set; }
        public Nullable<long> Pic_id_FK { get; set; }
        public string Pic_Log { get; set; }
        public Nullable<long> Creator_id_FK { get; set; }
        public Nullable<long> PinMessage_id_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupAdmin> tbl_GroupAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupBanList> tbl_GroupBanList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupMembers> tbl_GroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupMessage> tbl_GroupMessage { get; set; }
        public virtual tbl_Pic tbl_Pic { get; set; }
    }
}
