//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.tbl_BlockList = new HashSet<tbl_BlockList>();
            this.tbl_BlockList1 = new HashSet<tbl_BlockList>();
            this.tbl_CahnnelAdmins = new HashSet<tbl_CahnnelAdmins>();
            this.tbl_ChannelMembers = new HashSet<tbl_ChannelMembers>();
            this.tbl_ChannelMessages = new HashSet<tbl_ChannelMessages>();
            this.tbl_Channels = new HashSet<tbl_Channels>();
            this.tbl_Contact = new HashSet<tbl_Contact>();
            this.tbl_Contact1 = new HashSet<tbl_Contact>();
            this.tbl_GroupAdmin = new HashSet<tbl_GroupAdmin>();
            this.tbl_GroupAdmin1 = new HashSet<tbl_GroupAdmin>();
            this.tbl_GroupBanList = new HashSet<tbl_GroupBanList>();
            this.tbl_GroupBanList1 = new HashSet<tbl_GroupBanList>();
            this.tbl_GroupMembers = new HashSet<tbl_GroupMembers>();
            this.tbl_GroupMessage = new HashSet<tbl_GroupMessage>();
            this.tbl_OpenSessions = new HashSet<tbl_OpenSessions>();
            this.tbl_PrivateChat = new HashSet<tbl_PrivateChat>();
            this.tbl_PrivateChat1 = new HashSet<tbl_PrivateChat>();
            this.tbl_PrivateChatMessage = new HashSet<tbl_PrivateChatMessage>();
            this.tbl_Seen = new HashSet<tbl_Seen>();
        }
    
        public long id { get; set; }
        public string PhoneNumber { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Username { get; set; }
        public string EMail { get; set; }
        public string Biography { get; set; }
        public Nullable<long> Pic_id_FK { get; set; }
        public string Pic_Log { get; set; }
        public string LastSeenDate { get; set; }
        public string LastSeenTime { get; set; }
        public Nullable<int> LastSeenPrivacy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BlockList> tbl_BlockList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BlockList> tbl_BlockList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CahnnelAdmins> tbl_CahnnelAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelMembers> tbl_ChannelMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelMessages> tbl_ChannelMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Channels> tbl_Channels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Contact> tbl_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Contact> tbl_Contact1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupAdmin> tbl_GroupAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupAdmin> tbl_GroupAdmin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupBanList> tbl_GroupBanList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupBanList> tbl_GroupBanList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupMembers> tbl_GroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupMessage> tbl_GroupMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OpenSessions> tbl_OpenSessions { get; set; }
        public virtual tbl_Pic tbl_Pic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrivateChat> tbl_PrivateChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrivateChat> tbl_PrivateChat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrivateChatMessage> tbl_PrivateChatMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Seen> tbl_Seen { get; set; }
    }
}
