//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OpenSessions
    {
        public long id { get; set; }
        public Nullable<long> User_id_FK { get; set; }
        public string IP { get; set; }
        public string OS { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Code { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
