//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GroupMessage
    {
        public long id { get; set; }
        public Nullable<long> Group_id_FK { get; set; }
        public Nullable<long> Message_id_FK { get; set; }
        public Nullable<long> Sender_id_FK { get; set; }
        public Nullable<bool> IsRecive { get; set; }
    
        public virtual tbl_Groups tbl_Groups { get; set; }
        public virtual tbl_Message tbl_Message { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
