//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public long id { get; set; }
        public Nullable<long> User_id_FK { get; set; }
        public Nullable<long> Contact_id_FK { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
    }
}
