//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ActivationCode
    {
        public long id { get; set; }
        public string Code { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsActivate { get; set; }
    }
}
