//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Message()
        {
            this.tbl_ChannelMessages = new HashSet<tbl_ChannelMessages>();
            this.tbl_Channels = new HashSet<tbl_Channels>();
            this.tbl_GroupMessage = new HashSet<tbl_GroupMessage>();
            this.tbl_PrivateChatMessage = new HashSet<tbl_PrivateChatMessage>();
            this.tbl_Seen = new HashSet<tbl_Seen>();
        }
    
        public long id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> Pic_id_FK { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelMessages> tbl_ChannelMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Channels> tbl_Channels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupMessage> tbl_GroupMessage { get; set; }
        public virtual tbl_Pic tbl_Pic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrivateChatMessage> tbl_PrivateChatMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Seen> tbl_Seen { get; set; }
    }
}
