//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaLikeTelegram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Channels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Channels()
        {
            this.tbl_CahnnelAdmins = new HashSet<tbl_CahnnelAdmins>();
            this.tbl_ChannelMembers = new HashSet<tbl_ChannelMembers>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Description { get; set; }
        public Nullable<long> Creator_id_FK { get; set; }
        public string InviteLink { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> Pic_id_FK { get; set; }
        public string Pic_Log { get; set; }
        public Nullable<long> PinMessage_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CahnnelAdmins> tbl_CahnnelAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChannelMembers> tbl_ChannelMembers { get; set; }
        public virtual tbl_ChannelMessages tbl_ChannelMessages { get; set; }
        public virtual tbl_Message tbl_Message { get; set; }
        public virtual tbl_Pic tbl_Pic { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
